//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModel_MovApp : DbContext
    {
        public DataModel_MovApp()
            : base("name=DataModel_MovApp")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Creators> Creators { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<MovieCheckBoxViewModels> MovieCheckBoxViewModels { get; set; }
        public virtual DbSet<MovieCreatorProfessions> MovieCreatorProfessions { get; set; }
        public virtual DbSet<MovieGenres> MovieGenres { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<MoviesViewModels> MoviesViewModels { get; set; }
        public virtual DbSet<Professions> Professions { get; set; }
        public virtual DbSet<ProfessionTypes> ProfessionTypes { get; set; }
    }
}
