//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesViewModels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoviesViewModels()
        {
            this.Creators = new HashSet<Creators>();
            this.MovieCheckBoxViewModels = new HashSet<MovieCheckBoxViewModels>();
            this.Professions = new HashSet<Professions>();
            this.ProfessionTypes = new HashSet<ProfessionTypes>();
        }
    
        public int MovieId { get; set; }
        public string Name { get; set; }
        public string Name_org { get; set; }
        public System.DateTime Premiere { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Creators> Creators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieCheckBoxViewModels> MovieCheckBoxViewModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professions> Professions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessionTypes> ProfessionTypes { get; set; }
    }
}
