//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieCheckBoxViewModels
    {
        public short CheckBoxId { get; set; }
        public string Name { get; set; }
        public bool Checked { get; set; }
        public Nullable<int> MoviesViewModel_MovieId { get; set; }
    
        public virtual MoviesViewModels MoviesViewModels { get; set; }
    }
}
