//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieCreatorProfessions
    {
        public int MovieCreatorProfessionId { get; set; }
        public int MovieId { get; set; }
        public int CreatorId { get; set; }
        public int ProfessionId { get; set; }
    
        public virtual Creators Creators { get; set; }
        public virtual Movies Movies { get; set; }
        public virtual Professions Professions { get; set; }
    }
}
