//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfessionTypes()
        {
            this.Professions = new HashSet<Professions>();
        }
    
        public int ProfessionTypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> MoviesViewModel_MovieId { get; set; }
    
        public virtual MoviesViewModels MoviesViewModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professions> Professions { get; set; }
    }
}
